---
title: "co"
author: "Siyan Pu"
date: "11/20/2021"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE, message=FALSE, warning=FALSE)
library(httr)
library(jsonlite)
library(dplyr)
library(tidyr)
library(lubridate)
library(ggplot2)
library(ggpubr)
```

airly all CO data preprocessing
```{r}
airly_cob <- read.csv("airly_co.csv", check.names = F)
airly_cob <- airly_cob %>%
  gather(sensor_id, CO, -c('Time')) %>%
  rename('date' = 'Time')
airly_cob <- airly_cob[,c(1,3,2)] 
airly_cob$sensor_id <- as.integer(airly_cob$sensor_id)

airly_coc <- read.csv("airly_co_nov.csv", check.names = F)
airly_coc <- airly_coc %>%
  gather(sensor_id, CO, -c('Time', 'mark')) %>%
  rename('date' = 'Time')
airly_coc$sensor_id <- as.integer(airly_coc$sensor_id)

airly_coc <- airly_coc %>%
  select(-mark)
airly_coc <- airly_coc[,c(1,3,2)]
```

```{r}
airly_coa <- read.csv("airly2.csv") %>%
  select(date, CO, sensor_id)
airly2 <- rbind(airly_coa, airly_cob, airly_coc)

#convert to EST time zone (before daylight saving, 7 hour difference)
airly2$time <- as.POSIXct(airly2$date, format="%Y-%m-%d %H:%M:%S", tz="EET")
airly2$time <- lubridate::with_tz(airly2$time, "America/New_York")

airly2$CO <- airly2$CO/1000
airly2$day <- date(strptime(airly2$time, format="%Y-%m-%d %H:%M:%S"))
airly2$hour <- hour(strptime(airly2$time, format="%Y-%m-%d %H:%M:%S"))
airly2$dayhour <- lubridate::ymd_h(format(as.POSIXct(airly2$time,format="%Y-%m-%d %H:%M:%S"),"%Y-%m-%d %H"))
airly2$sensor_id <- as.factor(airly2$sensor_id)
```

```{r}
airly_co <- airly2 %>%
  select(time, CO, day, dayhour, sensor_id)

# airly_co %>%
#   filter(is.na(day))
# 
# #1 value < 0
# airly_co %>%
#   filter(CO < 0)
# 
# #1407 values = 0, 2% of the data
# airly_co %>%
#   filter(CO == 0)
# 
# #1078 values 
# airly_co %>%
#   filter(sensor_id == '7205' & is.na(CO))
# 
# #1095 values NA, 2% of the data
# airly_co %>%
#   filter(is.na(CO))

airly_co <- airly_co %>%
  filter(!is.na(CO))

airly_co$CO[airly_co$CO < 0] <- 0

airly_co %>%
  group_by(dayhour) %>%
  summarise(ahourlyCO = mean(CO, na.rm = T)) %>%
  ggplot(aes(x=dayhour, y=ahourlyCO))+
  geom_line()

# airly_co %>%
#   filter(day >= '2021-10-27') %>%
#   group_by(dayhour) %>%
#   summarise(ahourlyCO = mean(CO, na.rm = T)) %>%
#   ggplot(aes(x=dayhour, y=ahourlyCO))+
#   geom_line()

airly_co %>%
  filter(day == '2021-09-17' & time >= '2021-09-17 18:00') %>%
  ggplot(aes(x=time, y=CO))+
  geom_line(aes(color=sensor_id))

```


```{r}
regular1 <- read.csv("regular1.csv")
regular1$day <- date(strptime(regular1$Date, format="%Y-%m-%d"))
regular1$hour <- hour(strptime(regular1$Time, format="%H:%M"))
regular1$time <- as.POSIXct(paste(regular1$day, regular1$Time), format="%Y-%m-%d %H:%M")
regular1$dayhour <- lubridate::ymd_h(format(as.POSIXct(regular1$time,format="%Y-%m-%d %H:%M:%S"),"%Y-%m-%d %H"))
```

```{r}
regular2 <- rbind(read.csv("regular_min_1020.csv"), read.csv("regular_min_1109.csv"))
regular2$day <- date(strptime(regular2$Date, format="%Y-%m-%d"))
regular2$hour <- hour(strptime(regular2$Time, format="%H:%M"))
regular2$time <- as.POSIXct(paste(regular2$day, regular2$Time), format="%Y-%m-%d %H:%M")
regular2$dayhour <- lubridate::ymd_h(format(as.POSIXct(regular2$time,format="%Y-%m-%d %H:%M:%S"),"%Y-%m-%d %H"))
```

all regular CO data inspection (processing without TRH)
```{r}
regular_coa <- regular1 %>%
  select(time, CO, day, dayhour)

regular_cob <- regular2 %>%
  select(time, CO, day, dayhour)

regular_co <- rbind(regular_coa, regular_cob)

#2525 values ' C ', 2.7% of the data
# regular_co %>%
#   filter(regular_co$CO == ' C ')

#dealing with data type and missing data
regular_co$CO[regular_co$CO == ' C '] <- NA
regular_co$CO <- as.numeric(regular_co$CO, na.rm = T)

#4568 values NA, 4.8% of the data
# regular_co %>%
#   filter(is.na(CO))
# 
# #2220 values 0, 2.3% of the data
# regular_co %>%
#   filter(CO == 0)
# 
# #2180 values < 0, 2.3% of the data
# regular_co %>%
#   filter(CO < 0)

regular_co$CO[regular_co$CO < 0] <- 0

regular_co %>%
  filter(day >= '2021-10-27') %>%
  group_by(dayhour) %>%
  summarise(rhourlyCO = mean(CO, na.rm = T)) %>%
  ggplot(aes(x=dayhour, y=rhourlyCO))+
  geom_line()

regular_co %>%
  filter(day == '2021-09-17' & time >= '2021-09-17 17:00') %>%
  ggplot(aes(x=time, y=CO))+
  geom_line()
```


Precision for CO
```{r}
temp1 <- airly_co %>%
  group_by(day) %>%
  summarise(dailyCO_all = mean(CO, na.rm = T))

temp2 <- airly_co %>%
  group_by(day, sensor_id) %>%
  summarise(dailyCO = mean(CO, na.rm = T))

CO <- merge(temp1, temp2, by = "day", all.x = T) %>%
  mutate(diff_square = (dailyCO_all-dailyCO)**2)

M <- n_distinct(CO$sensor_id)
N <- n_distinct(CO$day)

SD <- sqrt(sum(CO$diff_square) / (M*N-1))
SD/mean(airly2$CO, na.rm=T)*100
```

RMSE
```{r}
temp1 <- regular_co %>%
  group_by(day) %>%
  summarise(rdailyCO = mean(CO, na.rm = T))

temp2 <- airly_co %>%
  group_by(day, sensor_id) %>%
  summarise(dailyCO = mean(CO, na.rm = T))

CO <- merge(temp1, temp2, by = "day", all.x = T) %>%
  mutate(diff_square = (rdailyCO-dailyCO)**2) %>%
  na.omit()

M <- n_distinct(CO$sensor_id)
N <- n_distinct(CO$day)

RMSE <- sqrt(sum(CO$diff_square) / (M*N-1))
RMSE/mean(regular_co$CO, na.rm = T)*100
```

```{r}
airly_co %>%
  group_by(day, sensor_id) %>%
  summarise(adailyCO = mean(CO, na.rm = T)) %>%
  ggplot(aes(day, adailyCO))+
  geom_line(aes(color=sensor_id))
```

```{r}
temp2 <- regular_co %>%
  group_by(day) %>%
  summarise(rdailyCO = mean(CO, na.rm = T))

temp1 <- airly_co %>%
  group_by(day) %>%
  summarise(adailyCO = mean(CO, na.rm = T))

merge(temp1, temp2, by = "day") %>%
  ggplot(aes(day))+
  geom_line(aes(y=adailyCO, colour="airly"))+
  geom_line(aes(y=rdailyCO, colour="regular"))

```

7160 daily model
```{r}
temp1 <- airly_co %>%
  filter(sensor_id == '7160') %>%
  group_by(day) %>%
  summarise(adailyCO = mean(CO, na.rm = T))

merge(temp1, temp2, by = "day") %>%
  ggplot(aes(day))+
  geom_line(aes(y=adailyCO, colour="airly"))+
  geom_line(aes(y=rdailyCO, colour="regular"))

CO_day <- merge(temp1, temp2, by = "day")
cor(CO_day$adailyCO, CO_day$rdailyCO)
model1 <- lm(adailyCO ~ rdailyCO + 1, data = CO_day)
summary(model1)
```

```{r}
CO_7160 <- CO_day %>%
  mutate(corrected_CO = (adailyCO - coef(model1)[1][1]) / coef(model1)[2][1])
CO_7160 %>%
  ggplot(aes(day))+
  geom_line(aes(y=corrected_CO, colour="airly_c"))+
  geom_line(aes(y=rdailyCO, colour="regular"))
```

7205 daily model
```{r}
temp1 <- airly_co %>%
  filter(sensor_id == '7205' & !is.na(CO)) %>%
  group_by(day) %>%
  summarise(adailyCO = mean(CO, na.rm = T))

merge(temp1, temp2, by = "day") %>%
  ggplot(aes(day))+
  geom_line(aes(y=adailyCO, colour="airly"))+
  geom_line(aes(y=rdailyCO, colour="regular"))

CO_day <- merge(temp1, temp2, by = "day")
cor(CO_day$adailyCO, CO_day$rdailyCO)
model2 <- lm(adailyCO ~ rdailyCO + 1, data = CO_day)
summary(model2)
```

```{r}
CO_7205 <- CO_day %>%
  mutate(corrected_CO = (adailyCO - coef(model2)[1][1]) / coef(model2)[2][1])
CO_7205 %>%
  ggplot(aes(day))+
  geom_line(aes(y=corrected_CO, colour="airly_c"))+
  geom_line(aes(y=rdailyCO, colour="regular"))
```

7250 daily model
```{r}
temp1 <- airly_co %>%
  filter(sensor_id == '7250') %>%
  group_by(day) %>%
  summarise(adailyCO = mean(CO, na.rm = T))

merge(temp1, temp2, by = "day") %>%
  ggplot(aes(day))+
  geom_line(aes(y=adailyCO, colour="airly"))+
  geom_line(aes(y=rdailyCO, colour="regular"))

CO_day <- merge(temp1, temp2, by = "day")
cor(CO_day$adailyCO, CO_day$rdailyCO)
model3 <- lm(adailyCO ~ rdailyCO + 1, data = CO_day)
summary(model3)
```

```{r}
CO_7250 <- CO_day %>%
  mutate(corrected_CO = (adailyCO - coef(model3)[1][1]) / coef(model3)[2][1])
CO_7250 %>%
  ggplot(aes(day))+
  geom_line(aes(y=corrected_CO, colour="airly_c"))+
  geom_line(aes(y=rdailyCO, colour="regular"))
```

```{r}
r1 <- ggplot(model1, aes(x = rdailyCO, y = adailyCO)) + 
  geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  stat_regline_equation(label.x = 0.6, label.y = 1.5, aes(label = ..eq.label..)) +
  stat_regline_equation(label.x = 0.6, label.y = 1.3, aes(label = ..rr.label..)) +
  coord_fixed(xlim = c(0, 2), ylim = c(0, 2))
r2 <- ggplot(model2, aes(x = rdailyCO, y = adailyCO)) + 
  geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  stat_regline_equation(label.x = 0.6, label.y = 1.5, aes(label = ..eq.label..)) +
  stat_regline_equation(label.x = 0.6, label.y = 1.3, aes(label = ..rr.label..)) +
  coord_fixed(xlim = c(0, 2), ylim = c(0, 2))
r3 <- ggplot(model3, aes(x = rdailyCO, y = adailyCO)) + 
  geom_point() + 
  geom_smooth(method = "lm", se=FALSE) +
  stat_regline_equation(label.x = 0.6, label.y = 1.5, aes(label = ..eq.label..)) +
  stat_regline_equation(label.x = 0.6, label.y = 1.3, aes(label = ..rr.label..)) +
  coord_fixed(xlim = c(0, 2), ylim = c(0, 2))
ggarrange(r1, r2, r3,
          labels = c("7160", "7205", "7250"),
          ncol = 2, nrow = 2)
```

